import React from "react";
import { Search, Sparkles, CheckCircle2, ArrowRight } from "lucide-react";

const Main = () => {
  return (
    <div className="min-h-screen bg-slate-950 flex items-center justify-center p-6 font-sans">
      <div className="flex flex-col lg:flex-row gap-6 max-w-7xl w-full max-h-90vh">
        
        {/* LEFT CARD: Search Section */}
        <div className="flex-1 bg-slate-900/50 border border-slate-800 rounded-2xl p-8 flex flex-col justify-center">
          <span className="text-blue-400 text-sm font-medium px-3 py-1 bg-blue-500/10 rounded-full w-fit mb-6">
            The World's Most Comprehensive FM Knowledge Platform
          </span>
          
          <h1 className="text-white text-4xl md:text-5xl font-bold leading-tight mb-6">
            Describe Your FM Problem. <br />
            <span className="text-blue-500">Get Expert Solutions.</span>
          </h1>
          
          <p className="text-slate-400 text-lg mb-10 leading-relaxed">
            Instant access to <span className="text-white font-semibold">10,000+ expert answers</span> and <span className="text-white font-semibold">5,000+ diagnostic reports</span> — curated by FM professionals, not generated by AI.
          </p>

          {/* Search Input Box */}
          <div className="relative group">
            <div className="flex items-center bg-white rounded-xl p-2 shadow-2xl">
              <Search className="ml-4 text-slate-400" size={24} />
              <input 
                type="text" 
                placeholder="PPM completion rates are too low"
                className="w-full px-4 py-3 text-slate-600 focus:outline-none text-lg"
              />
              <button className="bg-orange-600 hover:bg-orange-700 text-white px-6 py-3 rounded-lg flex items-center gap-2 font-bold transition-all text-wrap">
                <Sparkles size={18} />
                Ask Sam
              </button>
            </div>
          </div>
        </div>

        {/* RIGHT CARD: Report Assessment */}
        <div className="w-full lg:w-[450px] bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl">
          <div className="flex justify-between items-start mb-6">
            <div className="flex gap-3 text-xs text-slate-500 font-medium">
              <span>FmSolve</span>
              <span>|</span>
              <span className="text-blue-400">Stability Report</span>
            </div>
            <div className="flex items-center gap-2 text-right">
              <CheckCircle2 className="text-emerald-500" size={18} />
              <div>
                <p className="text-white text-xs font-bold">Action Complete</p>
                <p className="text-slate-500 text-[10px]">Workflow mapping completed</p>
              </div>
            </div>
          </div>

          <h2 className="text-white text-xl font-bold mb-2">Operational Efficiency Assessment</h2>
          <div className="flex gap-2 mb-6">
            <span className="bg-orange-500/20 text-orange-400 text-[10px] font-bold px-2 py-0.5 rounded border border-orange-500/30">High Risk</span>
            <span className="text-slate-400 text-xs">Operational Delivery</span>
          </div>

          <div className="space-y-4 mb-8">
            <div>
              <p className="text-blue-500 text-[10px] font-bold uppercase tracking-wider mb-1">Diagnosis</p>
              <p className="text-slate-300 text-sm">Site operations showing 18% efficiency gap against benchmarks. Process bottlenecks identified in daily task allocation.</p>
            </div>

            <div>
              <p className="text-blue-500 text-[10px] font-bold uppercase tracking-wider mb-2">Immediate Actions</p>
              <div className="space-y-2">
                <div className="flex items-center gap-2 text-slate-500 line-through text-sm">
                  <div className="w-4 h-4 bg-emerald-500 rounded flex items-center justify-center">
                    <CheckCircle2 size={12} className="text-white" />
                  </div>
                  Map current operational workflows
                </div>
                <div className="flex items-center gap-2 text-slate-500 line-through text-sm">
                  <div className="w-4 h-4 bg-emerald-500 rounded flex items-center justify-center">
                    <CheckCircle2 size={12} className="text-white" />
                  </div>
                  Implement daily briefing process
                </div>
                <div className="flex items-center gap-2 text-slate-300 text-sm">
                  <div className="w-4 h-4 border border-slate-600 rounded"></div>
                  Deploy mobile task management
                </div>
              </div>
            </div>
          </div>

          {/* Metrics Grid */}
          <div className="grid grid-cols-3 gap-2 mb-6">
            <div className="bg-slate-800/50 p-3 rounded-lg border border-slate-700 text-center">
              <p className="text-white text-lg font-bold">72%</p>
              <p className="text-slate-500 text-[13px] mb-1 leading-tight">Task Completion</p>
              <p className="text-emerald-500 text-[13px]">↑ improving</p>
            </div>
            <div className="bg-slate-800/50 p-3 rounded-lg border border-slate-700 text-center">
              <p className="text-white text-lg font-bold">65%</p>
              <p className="text-slate-500 text-[13px] mb-1 leading-tight">Team Utilisation</p>
              <p className="text-emerald-500 text-[13px]">↑ improving</p>
            </div>
            <div className="bg-slate-800/50 p-3 rounded-lg border border-slate-700 text-center">
              <p className="text-white text-lg font-bold">2.4hrs</p>
              <p className="text-slate-500 text-[13px] mb-1 leading-tight">Response Time</p>
              <p className="text-rose-500 text-[13px]">↓ improving</p>
            </div>
          </div>

          <button className="w-full bg-orange-600 hover:bg-orange-700 text-white font-bold py-3 rounded-lg flex items-center justify-center gap-2 transition-all">
            Get Your Report <ArrowRight size={18} />
          </button>
        </div>

      </div>
    </div>
  );
};

export default Main;