import React from "react";
import { Search, Sparkles, CheckCircle2, ArrowRight } from "lucide-react";

const Main = () => {
  return (
    <>
      <div className="flex items-center justify-center min-h-screen p-6 font-DmSans bg-slate-950">
        <div className="flex flex-col w-full max-w-6xl gap-6 lg:flex-row max-h-90vh">
          {/* LEFT CARD: Search Section */}
          <div className="flex flex-col justify-center flex-1 p-8 border bg-slate-900/50 border-slate-800 rounded-2xl">
            <span className="px-3 py-1 mb-6 text-sm font-medium text-blue-400 rounded-full bg-blue-500/10 w-fit">
              The World's Most Comprehensive FM Knowledge Platform
            </span>

            <h1 className="mb-6 text-3xl font-bold leading-tight text-white md:text-4xl ">
              Describe Your FM Problem. <br />
              <span className="text-blue-500">Get Expert Solutions.</span>
            </h1>

            <p className="mb-10 text-lg leading-relaxed md:pb-20 text-slate-400">
              Instant access to{" "}
              <span className="font-semibold text-white">
                10,000+ expert answers
              </span>{" "}
              and{" "}
              <span className="font-semibold text-white">
                5,000+ diagnostic reports
              </span>{" "}
              — curated by FM professionals, not generated by AI.
            </p>

            {/* Search Input Box */}
            <div className="relative ">
              <div className="flex items-center p-2 bg-white shadow-2xl rounded-xl">
                <Search className="ml-4 text-slate-400" size={24} />
                <input
                  type="text"
                  placeholder="PPM completion rates are too low"
                  className="w-full px-4 py-3 text-lg text-[#3C5279] focus:outline-none"
                />
                <button className="flex items-center gap-2 px-6 py-3 font-bold text-white transition-all bg-orange-600 rounded-lg hover:bg-orange-700 whitespace-nowrap">
                  <Sparkles size={18} />
                  Ask some
                </button>
              </div>
            </div>
          </div>

          {/* RIGHT CARD: Report Assessment */}
          <div className="w-full lg:w-[450px] bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl">
            <div className="flex items-start justify-between mb-6">
              <div className="flex gap-3 text-xs font-medium text-slate-500">
                <span>FmSolve</span>
                <span>|</span>
                <span className="text-blue-400">Stability Report</span>
              </div>
              <div className="flex items-center gap-2 text-right">
                <CheckCircle2 className="text-emerald-500" size={18} />
                <div>
                  <p className="text-xs font-bold text-white">
                    Action Complete
                  </p>
                  <p className="text-slate-500 text-[10px]">
                    Workflow mapping completed
                  </p>
                </div>
              </div>
            </div>

            <h2 className="mb-2 text-xl font-bold text-white">
              Operational Efficiency Assessment
            </h2>
            <div className="flex gap-2 mb-6">
              <span className="bg-orange-500/20 text-orange-400 text-[10px] font-bold px-2 py-0.5 rounded border border-orange-500/30">
                High Risk
              </span>
              <span className="text-xs text-slate-400">
                Operational Delivery
              </span>
            </div>

            <div className="mb-8 space-y-4">
              <div>
                <p className="text-blue-500 text-[10px] font-bold uppercase tracking-wider mb-1">
                  Diagnosis
                </p>
                <p className="text-sm text-slate-300">
                  Site operations showing 18% efficiency gap against benchmarks.
                  Process bottlenecks identified in daily task allocation.
                </p>
              </div>

              <div>
                <p className="text-blue-500 text-[10px] font-bold uppercase tracking-wider mb-2">
                  Immediate Actions
                </p>
                <div className="space-y-2">
                  <div className="flex items-center gap-2 text-sm line-through text-slate-500">
                    <div className="flex items-center justify-center w-4 h-4 rounded bg-emerald-500">
                      <CheckCircle2 size={12} className="text-white" />
                    </div>
                    Map current operational workflows
                  </div>
                  <div className="flex items-center gap-2 text-sm line-through text-slate-500">
                    <div className="flex items-center justify-center w-4 h-4 rounded bg-emerald-500">
                      <CheckCircle2 size={12} className="text-white" />
                    </div>
                    Implement daily briefing process
                  </div>
                  <div className="flex items-center gap-2 text-sm text-slate-300">
                    <div className="w-4 h-4 border rounded border-slate-600"></div>
                    Deploy mobile task management
                  </div>
                </div>
              </div>
            </div>

            {/* Metrics Grid */}
            <div className="grid grid-cols-3 gap-2 mb-6">
              <div className="p-3 text-center border rounded-lg bg-slate-800/50 border-slate-700">
                <p className="text-lg font-bold text-white">72%</p>
                <p className="text-slate-500 text-[13px] mb-1 leading-tight">
                  Task Completion
                </p>
                <p className="text-emerald-500 text-[13px]">↑ improving</p>
              </div>
              <div className="p-3 text-center border rounded-lg bg-slate-800/50 border-slate-700">
                <p className="text-lg font-bold text-white">65%</p>
                <p className="text-slate-500 text-[13px] mb-1 leading-tight">
                  Team Utilisation
                </p>
                <p className="text-emerald-500 text-[13px]">↑ improving</p>
              </div>
              <div className="p-3 text-center border rounded-lg bg-slate-800/50 border-slate-700">
                <p className="text-lg font-bold text-white">2.4hrs</p>
                <p className="text-slate-500 text-[13px] mb-1 leading-tight">
                  Response Time
                </p>
                <p className="text-rose-500 text-[13px]">↓ improving</p>
              </div>
            </div>

            <button className="flex items-center justify-center w-full gap-2 py-3 font-bold text-white transition-all bg-orange-600 rounded-lg hover:bg-orange-700">
              Get Your Report <ArrowRight size={18} />
            </button>
          </div>
        </div>
      </div>
      <div>
        <div className="text-center">
          <p className="text-4xl md:text-5xl">
            Do You Manage Multiple Sites Across These Sectors?
          </p>
        </div>
        <div className="flex px-5 py-10 space-x-5 animate-loop-scroll whitespace-nowrap">
          <p className="inline px-4 py-2 text-white border-2 border-white rounded-md border-rounded-lg">
            hospitality
          </p>
          <p className="inline px-4 py-2 text-white border-2 border-white rounded-md border-rounded-lg">
            hospitality
          </p>
          <p className="inline px-4 py-2 text-white border-2 border-white rounded-md border-rounded-lg">
            hospitality
          </p>
          <p className="inline px-4 py-2 text-white border-2 border-white rounded-md border-rounded-lg">
            hospitality
          </p>
          <p className="inline px-4 py-2 text-white border-2 border-white rounded-md border-rounded-lg">
            hospitality
          </p>
          <p className="inline px-4 py-2 text-white border-2 border-white rounded-md border-rounded-lg">
            hospitality
          </p>
          <p className="inline px-4 py-2 text-white border-2 border-white rounded-md border-rounded-lg">
            hospitality
          </p>
          <p className="inline px-4 py-2 text-white border-2 border-white rounded-md border-rounded-lg">
            hospitality
          </p>
          <p className="inline px-4 py-2 text-white border-2 border-white rounded-md border-rounded-lg">
            hospitality
          </p>
          <p className="inline px-4 py-2 text-white border-2 border-white rounded-md border-rounded-lg">
            hospitality
          </p>
          <p className="inline px-4 py-2 text-white border-2 border-white rounded-md border-rounded-lg">
            hospitality
          </p>
          <p className="inline px-4 py-2 text-white border-2 border-white rounded-md border-rounded-lg">
            hospitality
          </p>
          <p className="inline px-4 py-2 text-white border-2 border-white rounded-md border-rounded-lg">
            hospitality
          </p>
          <p className="inline px-4 py-2 text-white border-2 border-white rounded-md border-rounded-lg">
            hospitality
          </p>
          <p className="inline px-4 py-2 text-white border-2 border-white rounded-md border-rounded-lg">
            hospitality
          </p>
        </div>
      </div>
    </>
  );
};

export default Main;
