import React, { useEffect, useRef, useState } from "react";
import { Search, Sparkles } from "lucide-react";
import Assesment from "@/components/Shared/Assesment";
import bgVideo from "/firevideo.mp4";

const Main = () => {
  const [showVideo, setShowVideo] = useState(true);
  const videoRef = useRef(null);

  useEffect(() => {
    const timer = setTimeout(() => {
      if (videoRef.current) {
        try {
          videoRef.current.pause();
        } catch (e) {
          console.log(e);
        }
      }
      setShowVideo(false);
    }, 20000);

    return () => clearTimeout(timer);
  }, []);

  return (
    <div className="flex justify-center px-4 pt-20 pb-20 sm:px-6 lg:px-8 font-DmSans dark:bg-slate-950">
      <div className="flex flex-col w-full max-w-6xl gap-4 lg:flex-row">
        {/* Left Content */}
        <div
          className={`
            relative overflow-hidden
            flex flex-col justify-center flex-1
            border border-slate-200 dark:border-slate-800
            rounded-2xl
            transition-colors
            p-4 sm:p-6 md:p-8
            ${
              showVideo
                ? "bg-white/70 text-white backdrop-blur-sm dark:bg-slate-900/50"
                : "bg-white dark:bg-slate-900/50"
            }
          `}
        >
          {/* Background Video */}
          {showVideo && (
            <video
              ref={videoRef}
              className="absolute inset-0 z-0 object-cover w-full h-full"
              autoPlay
              muted
              playsInline
            >
              <source src={bgVideo} type="video/mp4" />
            </video>
          )}

          {/* Content */}
          <div className="relative z-10">
            <span className="inline-block mb-4 px-3 py-1.5 text-xs sm:text-sm font-medium text-blue-600 rounded-full bg-blue-500/10 dark:text-blue-400">
              The World's Most Comprehensive FM Knowledge Platform
            </span>

            <h1
              className={`
                mb-4
                font-bold leading-tight
                text-2xl sm:text-3xl md:text-4xl
                ${showVideo ? "text-white" : "text-slate-900 dark:text-white"}
              `}
            >
              Describe Your FM Problem. <br />
              <span className="text-blue-600 dark:text-blue-500">
                Get Expert Solutions.
              </span>
            </h1>

            <p
              className={`
                mb-6
                leading-relaxed
                text-sm sm:text-base md:text-lg
                ${
                  showVideo
                    ? "text-white"
                    : "text-slate-600 dark:text-slate-400"
                }
              `}
            >
              Instant access to{" "}
              <span className="font-semibold text-blue-500 dark:text-white">
                10,000+ expert answers
              </span>{" "}
              and{" "}
              <span className="font-semibold text-blue-500 dark:text-white">
                5,000+ diagnostic reports
              </span>{" "}
              — curated by FM professionals, not generated by AI.
            </p>

            {/* Search */}
            <div>
              <div className="flex flex-col items-stretch gap-2 p-2 bg-white shadow-xl sm:flex-row sm:items-center sm:gap-0 dark:bg-slate-100 rounded-xl">
                <Search
                  className="hidden ml-4 text-slate-400 sm:block"
                  size={22}
                />

                <input
                  type="text"
                  placeholder="PPM completion rates are too low"
                  className="
                    w-full
                    px-4 py-2.5
                    text-sm sm:text-base
                    text-[#3C5279]
                    bg-transparent
                    focus:outline-none
                  "
                />

                <button
                  className="
                    flex items-center justify-center gap-2
                    w-full sm:w-auto
                    px-5 py-2.5
                    font-semibold text-white
                    bg-orange-600 rounded-lg
                    hover:bg-orange-700
                    whitespace-nowrap
                  "
                >
                  <Sparkles size={16} />
                  Ask Sam
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Right Section */}
        <Assesment />
      </div>
    </div>
  );
};

export default Main;
